{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.1678.0 (24.12)+2a034ab280bddf891eb7bb9ebfe6996f9c3a3196"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Medidas\",\"dCliente\",\"dVendedor\",\"dProdutos\",\"dPagamentos\",\"fVendas\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "d_calendario": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d calendario": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dCalendario": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_calendario.ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Ano"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.anomê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Ano-Mês"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "ano-mê": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano mê": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "d_calendario.anomê.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "Ano-Mês"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "ano - mê date hierarchy": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ano mê date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "d_calendario.anomê.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "Ano-Mês"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "ano - mê day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano-mê day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano mê day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "d_calendario.anomê.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "Ano-Mês"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "ano - mê month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano-mê month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano mê month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ano - mê mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "ano-mê mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "ano mê mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "d_calendario.anomê.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "Ano-Mês"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "ano - mê quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano-mê quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano mê quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ano - mê qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.857
                    }
                  },
                  {
                    "ano-mê qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.857
                    }
                  },
                  {
                    "ano mê qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.846
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  }
                ]
              },
              "d_calendario.anomê.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "Ano-Mês"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "ano - mê year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano-mê year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano mê year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ano - mê yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "ano-mê yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "ano mê yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "d_calendario.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "d_calendario.date.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "d_calendario.date.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.date.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.date.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.date.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.dia_da_semana": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Dia da Semana"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dia da semana": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Mês"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mê": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.número_do_dia_da_semana": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Número do Dia da Semana"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "número do dia da semana": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.número_do_mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Número do Mês"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "número do mê": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.tipo_de_dia": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Tipo de Dia"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "tipo de dia": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.trimestre": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Trimestre"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "trimestre": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d cliente": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dCliente": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_cliente.cidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCliente",
                    "ConceptualProperty": "cidade"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "cidade": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_cliente.email": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCliente",
                    "ConceptualProperty": "email"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "email": {
                      "State": "Generated"
                    }
                  },
                  {
                    "correspondence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "message": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "communication": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "d_cliente.estado": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCliente",
                    "ConceptualProperty": "estado"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "estado": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_cliente.id_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCliente",
                    "ConceptualProperty": "id_cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id cliente": {
                      "State": "Generated"
                    }
                  },
                  {
                    "id_cliente": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_cliente.nome": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCliente",
                    "ConceptualProperty": "nome"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nome": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_cliente.telefone": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCliente",
                    "ConceptualProperty": "telefone"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "telefone": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_pagamento": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dPagamentos"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d pagamento": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dPagamentos": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_pagamento.forma_pagamento": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dPagamentos",
                    "ConceptualProperty": "forma_pagamento"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "forma pagamento": {
                      "State": "Generated"
                    }
                  },
                  {
                    "forma_pagamento": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_pagamento.id_pagamento": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dPagamentos",
                    "ConceptualProperty": "id_pagamento"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id pagamento": {
                      "State": "Generated"
                    }
                  },
                  {
                    "id_pagamento": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_pagamento.id_venda": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dPagamentos",
                    "ConceptualProperty": "id_venda"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id venda": {
                      "State": "Generated"
                    }
                  },
                  {
                    "id_venda": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "venda": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "identification venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_pagamento.status_pagamento": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dPagamentos",
                    "ConceptualProperty": "status_pagamento"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "status pagamento": {
                      "State": "Generated"
                    }
                  },
                  {
                    "status_pagamento": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "category pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "importance pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "prestige pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "prominence pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "condition pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "class pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "grade pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "level pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "position pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "rank pagamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_produto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dProdutos"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d produto": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dProdutos": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_produto.categoria": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dProdutos",
                    "ConceptualProperty": "categoria"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "categoria": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_produto.estoque_disponivel": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dProdutos",
                    "ConceptualProperty": "estoque_disponivel"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "estoque disponivel": {
                      "State": "Generated"
                    }
                  },
                  {
                    "estoque_disponivel": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_produto.id_produto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dProdutos",
                    "ConceptualProperty": "id_produto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id produto": {
                      "State": "Generated"
                    }
                  },
                  {
                    "id_produto": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_produto.nome_produto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dProdutos",
                    "ConceptualProperty": "nome_produto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nome produto": {
                      "State": "Generated"
                    }
                  },
                  {
                    "nome_produto": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_produto.preco_unitario": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dProdutos",
                    "ConceptualProperty": "preco_unitario"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "preco unitario": {
                      "State": "Generated"
                    }
                  },
                  {
                    "preco_unitario": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_vendedor": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dVendedor"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d vendedor": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dVendedor": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_vendedor.email": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dVendedor",
                    "ConceptualProperty": "email"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "email": {
                      "State": "Generated"
                    }
                  },
                  {
                    "correspondence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "message": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "communication": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "d_vendedor.equipe": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dVendedor",
                    "ConceptualProperty": "equipe"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "equipe": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_vendedor.id_vendedor": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dVendedor",
                    "ConceptualProperty": "id_vendedor"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id vendedor": {
                      "State": "Generated"
                    }
                  },
                  {
                    "id_vendedor": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_vendedor.nome": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dVendedor",
                    "ConceptualProperty": "nome"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nome": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_vendedor.telefone": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dVendedor",
                    "ConceptualProperty": "telefone"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "telefone": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "f_venda": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "f venda": {
                      "State": "Generated"
                    }
                  },
                  {
                    "fVendas": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "venda": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "f_venda.data_venda": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "data_venda"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "data venda": {
                      "State": "Generated"
                    }
                  },
                  {
                    "data_venda": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "venda": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "information venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "fact venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "info venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "statistic venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "document venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "figure venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "record venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "f_venda.id_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "id_cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id cliente": {
                      "State": "Generated"
                    }
                  },
                  {
                    "id_cliente": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential cliente": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "f_venda.id_produto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "id_produto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id produto": {
                      "State": "Generated"
                    }
                  },
                  {
                    "id_produto": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential produto": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "f_venda.id_venda": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "id_venda"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id venda": {
                      "State": "Generated"
                    }
                  },
                  {
                    "id_venda": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "venda": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "identification venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential venda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "f_venda.id_vendedor": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "id_vendedor"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id vendedor": {
                      "State": "Generated"
                    }
                  },
                  {
                    "id_vendedor": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential vendedor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "f_venda.quantidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "quantidade"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "quantidade": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "f_venda.valor_total": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "valor_total"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "valor total": {
                      "State": "Generated"
                    }
                  },
                  {
                    "valor_total": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "valor aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "valor overall": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "f_venda.valor_unitario": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "fVendas",
                    "ConceptualProperty": "valor_unitario"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "valor unitario": {
                      "State": "Generated"
                    }
                  },
                  {
                    "valor_unitario": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "medida": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "medida": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida.column_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Column1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "column 1": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Column1": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "medida.faturamento_total": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "faturamento_total"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "faturamento total": {
                      "State": "Generated"
                    }
                  },
                  {
                    "faturamento_total": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "faturamento aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "faturamento overall": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "medida.ticket_medio": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "ticket_medio"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ticket medio": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ticket_medio": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "Ticket Médio": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "d_calendario_anomê_date_hierarchy_has_d_calendario_anomê_day": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.anomê.day"
                      },
                      "Subject": {
                        "Role": "d_calendario.anomê.date_hierarchy"
                      }
                    },
                    "ID": "ano__mê_date_hierarchies_have_ano__mê_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.anomê.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.anomê.date_hierarchy"
                    }
                  },
                  "d_calendario.anomê.day": {
                    "Target": {
                      "Entity": "d_calendario.anomê.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_anomê_date_hierarchy_has_d_calendario_anomê_month": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.anomê.month"
                      },
                      "Subject": {
                        "Role": "d_calendario.anomê.date_hierarchy"
                      }
                    },
                    "ID": "ano__mê_date_hierarchies_have_ano__mê_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.anomê.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.anomê.date_hierarchy"
                    }
                  },
                  "d_calendario.anomê.month": {
                    "Target": {
                      "Entity": "d_calendario.anomê.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_anomê_date_hierarchy_has_d_calendario_anomê_quarter": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.anomê.quarter"
                      },
                      "Subject": {
                        "Role": "d_calendario.anomê.date_hierarchy"
                      }
                    },
                    "ID": "ano__mê_date_hierarchies_have_ano__mê_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.anomê.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.anomê.date_hierarchy"
                    }
                  },
                  "d_calendario.anomê.quarter": {
                    "Target": {
                      "Entity": "d_calendario.anomê.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_anomê_date_hierarchy_has_d_calendario_anomê_year": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.anomê.year"
                      },
                      "Subject": {
                        "Role": "d_calendario.anomê.date_hierarchy"
                      }
                    },
                    "ID": "ano__mê_date_hierarchies_have_ano__mê_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.anomê.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.anomê.date_hierarchy"
                    }
                  },
                  "d_calendario.anomê.year": {
                    "Target": {
                      "Entity": "d_calendario.anomê.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_anomê_has_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.anomê.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "d_calendario.anomê"
                      }
                    },
                    "ID": "anomê_have_ano__mê_date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.anomê": {
                    "Target": {
                      "Entity": "d_calendario.anomê"
                    }
                  },
                  "d_calendario.anomê.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.anomê.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_date_hierarchy_has_d_calendario_date_day": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.day"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.date.date_hierarchy"
                    }
                  },
                  "d_calendario.date.day": {
                    "Target": {
                      "Entity": "d_calendario.date.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_date_hierarchy_has_d_calendario_date_month": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.month"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.date.date_hierarchy"
                    }
                  },
                  "d_calendario.date.month": {
                    "Target": {
                      "Entity": "d_calendario.date.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_date_hierarchy_has_d_calendario_date_quarter": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.quarter"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.date.date_hierarchy"
                    }
                  },
                  "d_calendario.date.quarter": {
                    "Target": {
                      "Entity": "d_calendario.date.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_date_hierarchy_has_d_calendario_date_year": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.year"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.date.date_hierarchy"
                    }
                  },
                  "d_calendario.date.year": {
                    "Target": {
                      "Entity": "d_calendario.date.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_has_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "d_calendario.date"
                      }
                    },
                    "ID": "dates_have_date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date": {
                    "Target": {
                      "Entity": "d_calendario.date"
                    }
                  },
                  "d_calendario.date.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.date.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_ano": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.ano"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.ano": {
                    "Target": {
                      "Entity": "d_calendario.ano"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_anomê": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.anomê"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_anomê",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.anomê": {
                    "Target": {
                      "Entity": "d_calendario.anomê"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_date": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.date": {
                    "Target": {
                      "Entity": "d_calendario.date"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_dia_da_semana": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.dia_da_semana"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_dia_da_semanas",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.dia_da_semana": {
                    "Target": {
                      "Entity": "d_calendario.dia_da_semana"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_mê": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.mê"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.mê": {
                    "Target": {
                      "Entity": "d_calendario.mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_número_do_dia_da_semana": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.número_do_dia_da_semana"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_número_do_dia_da_semanas",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.número_do_dia_da_semana": {
                    "Target": {
                      "Entity": "d_calendario.número_do_dia_da_semana"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_número_do_mê": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.número_do_mê"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_número_do_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.número_do_mê": {
                    "Target": {
                      "Entity": "d_calendario.número_do_mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_tipo_de_dia": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.tipo_de_dia"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_tipo_de_dias",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.tipo_de_dia": {
                    "Target": {
                      "Entity": "d_calendario.tipo_de_dia"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_trimestre": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.trimestre"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_trimestres",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.trimestre": {
                    "Target": {
                      "Entity": "d_calendario.trimestre"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_cliente_has_cidade": {
                "Binding": {
                  "ConceptualEntity": "dCliente"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente.cidade"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_cidades",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "d_cliente.cidade": {
                    "Target": {
                      "Entity": "d_cliente.cidade"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_cliente_has_email": {
                "Binding": {
                  "ConceptualEntity": "dCliente"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente.email"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_emails",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "d_cliente.email": {
                    "Target": {
                      "Entity": "d_cliente.email"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_cliente_has_estado": {
                "Binding": {
                  "ConceptualEntity": "dCliente"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente.estado"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_estado",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "d_cliente.estado": {
                    "Target": {
                      "Entity": "d_cliente.estado"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_cliente_has_id_cliente": {
                "Binding": {
                  "ConceptualEntity": "dCliente"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente.id_cliente"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_id_clientes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "d_cliente.id_cliente": {
                    "Target": {
                      "Entity": "d_cliente.id_cliente"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_cliente_has_nome": {
                "Binding": {
                  "ConceptualEntity": "dCliente"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente.nome"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_nome",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "d_cliente.nome": {
                    "Target": {
                      "Entity": "d_cliente.nome"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_cliente_has_telefone": {
                "Binding": {
                  "ConceptualEntity": "dCliente"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente.telefone"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_telefones",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "d_cliente.telefone": {
                    "Target": {
                      "Entity": "d_cliente.telefone"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_pagamento_has_f_venda": {
                "Binding": {
                  "ConceptualEntity": "dPagamentos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda"
                      },
                      "Subject": {
                        "Role": "d_pagamento"
                      }
                    },
                    "ID": "d_pagamentos_have_f_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_pagamento": {
                    "Target": {
                      "Entity": "d_pagamento"
                    }
                  },
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_pagamento_has_forma_pagamento": {
                "Binding": {
                  "ConceptualEntity": "dPagamentos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_pagamento.forma_pagamento"
                      },
                      "Subject": {
                        "Role": "d_pagamento"
                      }
                    },
                    "ID": "d_pagamentos_have_forma_pagamentos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_pagamento": {
                    "Target": {
                      "Entity": "d_pagamento"
                    }
                  },
                  "d_pagamento.forma_pagamento": {
                    "Target": {
                      "Entity": "d_pagamento.forma_pagamento"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_pagamento_has_id_pagamento": {
                "Binding": {
                  "ConceptualEntity": "dPagamentos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_pagamento.id_pagamento"
                      },
                      "Subject": {
                        "Role": "d_pagamento"
                      }
                    },
                    "ID": "d_pagamentos_have_id_pagamentos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_pagamento": {
                    "Target": {
                      "Entity": "d_pagamento"
                    }
                  },
                  "d_pagamento.id_pagamento": {
                    "Target": {
                      "Entity": "d_pagamento.id_pagamento"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_pagamento_has_id_venda": {
                "Binding": {
                  "ConceptualEntity": "dPagamentos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_pagamento.id_venda"
                      },
                      "Subject": {
                        "Role": "d_pagamento"
                      }
                    },
                    "ID": "d_pagamentos_have_id_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_pagamento": {
                    "Target": {
                      "Entity": "d_pagamento"
                    }
                  },
                  "d_pagamento.id_venda": {
                    "Target": {
                      "Entity": "d_pagamento.id_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_pagamento_has_status_pagamento": {
                "Binding": {
                  "ConceptualEntity": "dPagamentos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_pagamento.status_pagamento"
                      },
                      "Subject": {
                        "Role": "d_pagamento"
                      }
                    },
                    "ID": "d_pagamentos_have_status_pagamentos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_pagamento": {
                    "Target": {
                      "Entity": "d_pagamento"
                    }
                  },
                  "d_pagamento.status_pagamento": {
                    "Target": {
                      "Entity": "d_pagamento.status_pagamento"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_produto_has_categoria": {
                "Binding": {
                  "ConceptualEntity": "dProdutos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_produto.categoria"
                      },
                      "Subject": {
                        "Role": "d_produto"
                      }
                    },
                    "ID": "d_produtos_have_categorias",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_produto": {
                    "Target": {
                      "Entity": "d_produto"
                    }
                  },
                  "d_produto.categoria": {
                    "Target": {
                      "Entity": "d_produto.categoria"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_produto_has_estoque_disponivel": {
                "Binding": {
                  "ConceptualEntity": "dProdutos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_produto.estoque_disponivel"
                      },
                      "Subject": {
                        "Role": "d_produto"
                      }
                    },
                    "ID": "d_produtos_have_estoque_disponivels",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_produto": {
                    "Target": {
                      "Entity": "d_produto"
                    }
                  },
                  "d_produto.estoque_disponivel": {
                    "Target": {
                      "Entity": "d_produto.estoque_disponivel"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_produto_has_id_produto": {
                "Binding": {
                  "ConceptualEntity": "dProdutos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_produto.id_produto"
                      },
                      "Subject": {
                        "Role": "d_produto"
                      }
                    },
                    "ID": "d_produtos_have_id_produtos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_produto": {
                    "Target": {
                      "Entity": "d_produto"
                    }
                  },
                  "d_produto.id_produto": {
                    "Target": {
                      "Entity": "d_produto.id_produto"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_produto_has_nome_produto": {
                "Binding": {
                  "ConceptualEntity": "dProdutos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_produto.nome_produto"
                      },
                      "Subject": {
                        "Role": "d_produto"
                      }
                    },
                    "ID": "d_produtos_have_nome_produtos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_produto": {
                    "Target": {
                      "Entity": "d_produto"
                    }
                  },
                  "d_produto.nome_produto": {
                    "Target": {
                      "Entity": "d_produto.nome_produto"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_produto_has_preco_unitario": {
                "Binding": {
                  "ConceptualEntity": "dProdutos"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_produto.preco_unitario"
                      },
                      "Subject": {
                        "Role": "d_produto"
                      }
                    },
                    "ID": "d_produtos_have_preco_unitarios",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_produto": {
                    "Target": {
                      "Entity": "d_produto"
                    }
                  },
                  "d_produto.preco_unitario": {
                    "Target": {
                      "Entity": "d_produto.preco_unitario"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_vendedor_has_email": {
                "Binding": {
                  "ConceptualEntity": "dVendedor"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_vendedor.email"
                      },
                      "Subject": {
                        "Role": "d_vendedor"
                      }
                    },
                    "ID": "d_vendedors_have_emails",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_vendedor": {
                    "Target": {
                      "Entity": "d_vendedor"
                    }
                  },
                  "d_vendedor.email": {
                    "Target": {
                      "Entity": "d_vendedor.email"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_vendedor_has_equipe": {
                "Binding": {
                  "ConceptualEntity": "dVendedor"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_vendedor.equipe"
                      },
                      "Subject": {
                        "Role": "d_vendedor"
                      }
                    },
                    "ID": "d_vendedors_have_equipes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_vendedor": {
                    "Target": {
                      "Entity": "d_vendedor"
                    }
                  },
                  "d_vendedor.equipe": {
                    "Target": {
                      "Entity": "d_vendedor.equipe"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_vendedor_has_id_vendedor": {
                "Binding": {
                  "ConceptualEntity": "dVendedor"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_vendedor.id_vendedor"
                      },
                      "Subject": {
                        "Role": "d_vendedor"
                      }
                    },
                    "ID": "d_vendedors_have_id_vendedors",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_vendedor": {
                    "Target": {
                      "Entity": "d_vendedor"
                    }
                  },
                  "d_vendedor.id_vendedor": {
                    "Target": {
                      "Entity": "d_vendedor.id_vendedor"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_vendedor_has_nome": {
                "Binding": {
                  "ConceptualEntity": "dVendedor"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_vendedor.nome"
                      },
                      "Subject": {
                        "Role": "d_vendedor"
                      }
                    },
                    "ID": "d_vendedors_have_nome",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_vendedor": {
                    "Target": {
                      "Entity": "d_vendedor"
                    }
                  },
                  "d_vendedor.nome": {
                    "Target": {
                      "Entity": "d_vendedor.nome"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_vendedor_has_telefone": {
                "Binding": {
                  "ConceptualEntity": "dVendedor"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_vendedor.telefone"
                      },
                      "Subject": {
                        "Role": "d_vendedor"
                      }
                    },
                    "ID": "d_vendedors_have_telefones",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_vendedor": {
                    "Target": {
                      "Entity": "d_vendedor"
                    }
                  },
                  "d_vendedor.telefone": {
                    "Target": {
                      "Entity": "d_vendedor.telefone"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_d_calendario": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_d_calendarios",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_f_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_d_cliente": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_cliente"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_d_clientes",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda"
                      },
                      "Subject": {
                        "Role": "d_cliente"
                      }
                    },
                    "ID": "d_clientes_have_f_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_cliente": {
                    "Target": {
                      "Entity": "d_cliente"
                    }
                  },
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_d_pagamento": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_pagamento"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_d_pagamentos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_pagamento": {
                    "Target": {
                      "Entity": "d_pagamento"
                    }
                  },
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_d_produto": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_produto"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_d_produtos",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda"
                      },
                      "Subject": {
                        "Role": "d_produto"
                      }
                    },
                    "ID": "d_produtos_have_f_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_produto": {
                    "Target": {
                      "Entity": "d_produto"
                    }
                  },
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_d_vendedor": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_vendedor"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_d_vendedors",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda"
                      },
                      "Subject": {
                        "Role": "d_vendedor"
                      }
                    },
                    "ID": "d_vendedors_have_f_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_vendedor": {
                    "Target": {
                      "Entity": "d_vendedor"
                    }
                  },
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_data_venda": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda.data_venda"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_data_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "f_venda.data_venda": {
                    "Target": {
                      "Entity": "f_venda.data_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_id_venda": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda.id_venda"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_id_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "f_venda.id_venda": {
                    "Target": {
                      "Entity": "f_venda.id_venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_medida_faturamento_total": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.faturamento_total"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_faturamento_total",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "medida.faturamento_total": {
                    "Target": {
                      "Entity": "medida.faturamento_total"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_medida_ticket_medio": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.ticket_medio"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_ticket_medio",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "medida.ticket_medio": {
                    "Target": {
                      "Entity": "medida.ticket_medio"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_quantidade": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda.quantidade"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_quantidades",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "f_venda.quantidade": {
                    "Target": {
                      "Entity": "f_venda.quantidade"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_valor_total": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda.valor_total"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_valor_totals",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "f_venda.valor_total": {
                    "Target": {
                      "Entity": "f_venda.valor_total"
                    }
                  }
                },
                "State": "Generated"
              },
              "f_venda_has_valor_unitario": {
                "Binding": {
                  "ConceptualEntity": "fVendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "f_venda.valor_unitario"
                      },
                      "Subject": {
                        "Role": "f_venda"
                      }
                    },
                    "ID": "f_venda_have_valor_unitarios",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "f_venda": {
                    "Target": {
                      "Entity": "f_venda"
                    }
                  },
                  "f_venda.valor_unitario": {
                    "Target": {
                      "Entity": "f_venda.valor_unitario"
                    }
                  }
                },
                "State": "Generated"
              },
              "medida_has_column_1": {
                "Binding": {
                  "ConceptualEntity": "Medidas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.column_1"
                      },
                      "Subject": {
                        "Role": "medida"
                      }
                    },
                    "ID": "medidas_have_column_1",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medida": {
                    "Target": {
                      "Entity": "medida"
                    }
                  },
                  "medida.column_1": {
                    "Target": {
                      "Entity": "medida.column_1"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_066e2a5f-ebb2-4664-8fb5-b6d25ef28ed2",
        "fromColumn": "id_cliente",
        "fromTable": "fVendas",
        "toColumn": "id_cliente",
        "toTable": "dCliente"
      },
      {
        "name": "AutoDetected_7c4d8562-c884-4534-88d7-49d061765cdd",
        "fromColumn": "id_vendedor",
        "fromTable": "fVendas",
        "toColumn": "id_vendedor",
        "toTable": "dVendedor"
      },
      {
        "name": "AutoDetected_6fb0aca6-57b6-41ce-904c-3dce410dc7e6",
        "fromColumn": "id_produto",
        "fromTable": "fVendas",
        "toColumn": "id_produto",
        "toTable": "dProdutos"
      },
      {
        "name": "41ee2ac9-f229-4773-adcd-6b0ad7fbebb5",
        "fromColumn": "Date",
        "fromTable": "dCalendario",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4bac44d9-8f08-495b-b7d6-870187b1159b"
      },
      {
        "name": "ee2e1f27-127a-479c-bed9-02a4520b80f7",
        "fromColumn": "Ano-Mês",
        "fromTable": "dCalendario",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b2397acb-0929-4697-96e3-a6662f7a4a3c"
      },
      {
        "name": "9204eed4-4876-df07-3a12-abe092d065fb",
        "fromColumn": "data_venda",
        "fromTable": "fVendas",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "AutoDetected_116cb1a5-f018-4707-bb1f-63d13f086e81",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "id_venda",
        "fromTable": "dPagamentos",
        "toColumn": "id_venda",
        "toTable": "fVendas"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dCliente",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id_cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f2bf1e8-28da-49fa-a291-1f2c9163a9e4",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f479a99b-7122-4d79-bc30-038978cbcbdc",
            "sourceColumn": "nome",
            "summarizeBy": "none"
          },
          {
            "name": "email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1804928b-e7c1-4e71-9af8-7506613336ce",
            "sourceColumn": "email",
            "summarizeBy": "none"
          },
          {
            "name": "telefone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6e3d5c4-0b21-44ed-9e1a-583c697aa4de",
            "sourceColumn": "telefone",
            "summarizeBy": "none"
          },
          {
            "name": "cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38dbc3ba-f73d-438e-b5cf-06c4b7fa8f9c",
            "sourceColumn": "cidade",
            "summarizeBy": "none"
          },
          {
            "name": "estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0d5600a-8faa-4889-afd0-187df50872d3",
            "sourceColumn": "estado",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "74d1f7d3-fc7b-428e-bcc7-0a9730e012a4",
        "partitions": [
          {
            "name": "dCliente",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Web.BrowserContents(\"https://docs.google.com/spreadsheets/d/e/2PACX-1vQcA7MuyQioSGW9kBkg0HzGaQRkuHdjZk4cQf1pEZ5fPVv_lg6D2oFt2sHHixhgtw/pubhtml\"),",
                "    #\"Extracted Table From Html\" = Html.Table(Source, {{\"Column1\", \"DIV:nth-child(1) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(1)\"}, {\"Column2\", \"DIV:nth-child(1) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(2)\"}, {\"Column3\", \"DIV:nth-child(1) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(3)\"}, {\"Column4\", \"DIV:nth-child(1) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(4)\"}, {\"Column5\", \"DIV:nth-child(1) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(5)\"}, {\"Column6\", \"DIV:nth-child(1) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(6)\"}, {\"Column7\", \"DIV:nth-child(1) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(7)\"}}, [RowSelector=\"DIV:nth-child(1) > DIV.ritz.grid-container > TABLE.waffle > * > TR\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Extracted Table From Html\",{{\"Column1\", Int64.Type}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Changed Type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Removed Blank Rows\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"1\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"nome\", type text}, {\"email\", type text}, {\"telefone\", type text}, {\"cidade\", type text}, {\"estado\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"1\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"id_cliente\", type text}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dVendedor",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id_vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38bbba23-d45b-4da5-bd58-08209423ac03",
            "sourceColumn": "id_vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cba81f4a-ac97-4467-950e-e395f608a033",
            "sourceColumn": "nome",
            "summarizeBy": "none"
          },
          {
            "name": "email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38758981-daae-431b-bd3f-e01d44d58ca5",
            "sourceColumn": "email",
            "summarizeBy": "none"
          },
          {
            "name": "telefone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc90591c-17c8-4b53-b9ea-5157271cf1c8",
            "sourceColumn": "telefone",
            "summarizeBy": "none"
          },
          {
            "name": "equipe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2099d974-ccd1-4462-9dbf-81239bb8804c",
            "sourceColumn": "equipe",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "003d1793-c857-4a5a-a821-030e9630e37b",
        "partitions": [
          {
            "name": "dVendedor",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Web.BrowserContents(\"https://docs.google.com/spreadsheets/d/e/2PACX-1vQcA7MuyQioSGW9kBkg0HzGaQRkuHdjZk4cQf1pEZ5fPVv_lg6D2oFt2sHHixhgtw/pubhtml\"),",
                "    #\"Extracted Table From Html\" = Html.Table(Source, {{\"Column1\", \"DIV:nth-child(2) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(1)\"}, {\"Column2\", \"DIV:nth-child(2) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(2)\"}, {\"Column3\", \"DIV:nth-child(2) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(3)\"}, {\"Column4\", \"DIV:nth-child(2) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(4)\"}, {\"Column5\", \"DIV:nth-child(2) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(5)\"}, {\"Column6\", \"DIV:nth-child(2) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(6)\"}}, [RowSelector=\"DIV:nth-child(2) > DIV.ritz.grid-container > TABLE.waffle > * > TR\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Extracted Table From Html\",{{\"Column1\", Int64.Type}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Changed Type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Blank Rows\",{\"Column1\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Removed Columns\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"id_vendedor\", Int64.Type}, {\"nome\", type text}, {\"email\", type text}, {\"telefone\", type text}, {\"equipe\", type text}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Changed Type1\",{{\"id_vendedor\", type text}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dProdutos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id_produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81ec6e52-dee9-460c-a1d2-7afa81625a3c",
            "sourceColumn": "id_produto",
            "summarizeBy": "none"
          },
          {
            "name": "nome_produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02eec518-b993-461b-bcc2-6748e6247967",
            "sourceColumn": "nome_produto",
            "summarizeBy": "none"
          },
          {
            "name": "categoria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17af324b-c3a6-4ae7-9869-47d1f6c90bfb",
            "sourceColumn": "categoria",
            "summarizeBy": "none"
          },
          {
            "name": "preco_unitario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "af08f741-e5ee-415e-acdf-d1ea71d8c84a",
            "sourceColumn": "preco_unitario",
            "summarizeBy": "none"
          },
          {
            "name": "estoque_disponivel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b9ab82a5-63b1-4ff2-ba22-4b76368fe6df",
            "sourceColumn": "estoque_disponivel",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d7cf9057-0b9d-4903-87e8-a6b72f900883",
        "partitions": [
          {
            "name": "dProdutos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Web.BrowserContents(\"https://docs.google.com/spreadsheets/d/e/2PACX-1vQcA7MuyQioSGW9kBkg0HzGaQRkuHdjZk4cQf1pEZ5fPVv_lg6D2oFt2sHHixhgtw/pubhtml\"),",
                "    #\"Extracted Table From Html\" = Html.Table(Source, {{\"Column1\", \"DIV:nth-child(3) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(1)\"}, {\"Column2\", \"DIV:nth-child(3) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(2)\"}, {\"Column3\", \"DIV:nth-child(3) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(3)\"}, {\"Column4\", \"DIV:nth-child(3) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(4)\"}, {\"Column5\", \"DIV:nth-child(3) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(5)\"}, {\"Column6\", \"DIV:nth-child(3) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(6)\"}}, [RowSelector=\"DIV:nth-child(3) > DIV.ritz.grid-container > TABLE.waffle > * > TR\"]),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Extracted Table From Html\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Blank Rows\",{\"Column1\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Removed Columns\", [PromoteAllScalars=true]),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Promoted Headers\",\",\",\".\",Replacer.ReplaceText,{\"preco_unitario\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"preco_unitario\", type number}, {\"estoque_disponivel\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fVendas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id_venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f13b51e-df31-45ea-9e61-3dfb54a7212d",
            "sourceColumn": "id_venda",
            "summarizeBy": "none"
          },
          {
            "name": "data_venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f87793ee-e284-489a-ac55-6b6cb47c49c2",
            "sourceColumn": "data_venda",
            "summarizeBy": "none"
          },
          {
            "name": "id_cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "601e6334-35af-40df-aaa5-54554d1ba035",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "id_vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1508d8d-6cef-4f5e-a750-bb6eb25f7125",
            "sourceColumn": "id_vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "id_produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b44bfd2f-bc94-4c22-b26f-b4a27a8c2172",
            "sourceColumn": "id_produto",
            "summarizeBy": "none"
          },
          {
            "name": "quantidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "baab097c-87a9-4590-9e18-b89073ecf637",
            "sourceColumn": "quantidade",
            "summarizeBy": "none"
          },
          {
            "name": "valor_unitario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e8b798cc-13c2-4763-aa2d-e2d46b840549",
            "sourceColumn": "valor_unitario",
            "summarizeBy": "sum"
          },
          {
            "name": "valor_total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4770d515-d7ef-4ee3-9c6a-84b42771b43e",
            "sourceColumn": "valor_total",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "515d79da-4cb9-4e31-aa7c-605d76f81b3d",
        "partitions": [
          {
            "name": "fVendas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Web.BrowserContents(\"https://docs.google.com/spreadsheets/d/e/2PACX-1vQcA7MuyQioSGW9kBkg0HzGaQRkuHdjZk4cQf1pEZ5fPVv_lg6D2oFt2sHHixhgtw/pubhtml\"),",
                "    #\"Extracted Table From Html\" = Html.Table(Source, {{\"Column1\", \"DIV:nth-child(4) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(1)\"}, {\"Column2\", \"DIV:nth-child(4) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(2)\"}, {\"Column3\", \"DIV:nth-child(4) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(3)\"}, {\"Column4\", \"DIV:nth-child(4) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(4)\"}, {\"Column5\", \"DIV:nth-child(4) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(5)\"}, {\"Column6\", \"DIV:nth-child(4) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(6)\"}, {\"Column7\", \"DIV:nth-child(4) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(7)\"}, {\"Column8\", \"DIV:nth-child(4) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(8)\"}, {\"Column9\", \"DIV:nth-child(4) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(9)\"}}, [RowSelector=\"DIV:nth-child(4) > DIV.ritz.grid-container > TABLE.waffle > * > TR\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Extracted Table From Html\",{{\"Column1\", Int64.Type}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Changed Type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Blank Rows\",{\"Column1\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Removed Columns\", [PromoteAllScalars=true]),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Promoted Headers\",\",\",\".\",Replacer.ReplaceText,{\"valor_unitario\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"valor_unitario\", type number}}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Changed Type1\",\",\",\".\",Replacer.ReplaceText,{\"valor_total\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"valor_total\", type number}, {\"data_venda\", type date}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ae0caa18-dd22-41f0-9696-8cd350baa481",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d553d9a5-fe3b-495b-997e-9d913176d5fb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cf407f1f-a449-4659-bb71-8d1d410c523c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1e63892c-92c3-484e-a9dc-acf7e53d7c89",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "cf343aae-8d27-4ce3-88ed-c4fc5422d3ed",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0119eb87-38e6-4918-a664-d47675a97b1a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "324a5c52-034a-4415-8b3a-ab566a4ed7a1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f66b75f8-6d59-45b2-af49-b921db4aa3b0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cdb386fb-a9f9-4553-9111-f85f3a0d8cff",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "60ab523e-e41c-4c66-833e-51e9c8579b44",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d67fe358-ae20-4a0b-8df5-0f4f90c78509",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "05ca1deb-1066-468e-b6b0-63c67b596668",
                "ordinal": 3
              }
            ],
            "lineageTag": "77bc981e-e6c6-4010-b2e0-37812ac2061a"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "db3d419f-c5f6-4a7e-8cb9-960c599f82d9",
        "partitions": [
          {
            "name": "DateTableTemplate_ae0caa18-dd22-41f0-9696-8cd350baa481",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e150cb8f24514f8082a936eca8acf1b2"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ff64fb5c-86ac-4e76-a127-a94b9e3deef9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4bac44d9-8f08-495b-b7d6-870187b1159b"
                },
                "isDefault": true,
                "relationship": "41ee2ac9-f229-4773-adcd-6b0ad7fbebb5"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d5e1ca4e-2c53-4f60-8283-5a9197efa29c",
            "sourceColumn": "[Ano]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "56afc8ea-78b1-45c4-9792-c93fd78d8847",
            "sourceColumn": "[Mês]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Número do Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6635ba0f-be52-4625-baad-fa0bbe6b34b2",
            "sourceColumn": "[Número do Mês]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "498b4b0c-14e4-49f5-9510-69b5ce95797e",
            "sourceColumn": "[Trimestre]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano-Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Mm/yyyy",
            "isNameInferred": true,
            "lineageTag": "216b5985-9936-41bf-b8b6-4ceab4abf6b9",
            "sourceColumn": "[Ano-Mês]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b2397acb-0929-4697-96e3-a6662f7a4a3c"
                },
                "isDefault": true,
                "relationship": "ee2e1f27-127a-479c-bed9-02a4520b80f7"
              }
            ]
          },
          {
            "name": "Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5684c3dc-3d8b-40e9-83ee-810d9f6e1eb5",
            "sourceColumn": "[Dia da Semana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Número do Dia da Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "00cb9802-322f-4324-aff2-0009d32b041d",
            "sourceColumn": "[Número do Dia da Semana]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Tipo de Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5f7ff096-352a-42de-bb17-b75cf6d50a05",
            "sourceColumn": "[Tipo de Dia]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "cab1aeff-c517-4f74-9875-30ddb9b83880",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS (",
                "    CALENDAR ( MIN(fVendas[data_venda]), MAX(fVendas[data_venda]) ),",
                "    \"Ano\", YEAR([Date]),",
                "    \"Mês\", FORMAT([Date], \"mmmm\"),",
                "    \"Número do Mês\", MONTH([Date]),",
                "    \"Trimestre\", \"T\" & FORMAT([Date], \"Q\"),",
                "    \"Ano-Mês\", FORMAT([Date], \"YYYY-MM\"),",
                "    \"Dia da Semana\", FORMAT([Date], \"dddd\"),",
                "    \"Número do Dia da Semana\", WEEKDAY([Date], 2),",
                "    \"Tipo de Dia\", IF(WEEKDAY([Date], 2) >= 6, \"Fim de Semana\", \"Meio de Semana\")",
                "",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4bac44d9-8f08-495b-b7d6-870187b1159b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "013c0d7c-5e65-4d12-8249-2928effb484d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e93021b8-180d-46d4-9fdf-b32d77855f01",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8a54d2b8-f35c-4586-806e-d109526674b9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5fd93629-653c-4f32-882c-0b44ccc726f6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9da8f277-32b0-4ea2-9feb-d7d4ed911064",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d11350f7-72d1-49b6-8bd2-841f7b09cd20",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fae11788-a3e9-4408-b561-585e50d47b19",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6984efe3-a916-4a7f-ae46-e65e52863a32",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e600e878-84a3-45c8-9fa2-19cf2ad02804",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f4845569-7557-484f-88eb-8884c65cd060",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fcc0a565-f104-486a-a0fb-d58406d535bb",
                "ordinal": 3
              }
            ],
            "lineageTag": "3ededbc2-1771-4b75-bc99-17e264928b97"
          }
        ],
        "isHidden": true,
        "lineageTag": "8a6c346d-d79d-41ef-ada2-08252c7a0b89",
        "partitions": [
          {
            "name": "LocalDateTable_4bac44d9-8f08-495b-b7d6-870187b1159b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendario'[Date])), 1, 1), Date(Year(MAX('dCalendario'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b2397acb-0929-4697-96e3-a6662f7a4a3c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5ddca8ec-6f54-4d91-97a1-a15edfee2276",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "075d3918-e702-470a-82e2-49042eee2954",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e67a11a0-a7f1-4122-851d-f24ff2ca344d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "285832be-88c1-4865-959e-c68e44e51a9f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "959c950b-5559-456f-ad3f-4f640a4411af",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "03046409-cd0a-4182-b0e9-206db171075a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f2a5a5fe-7b54-4f6b-9d16-66e3fa32d9fb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "624bb607-7f1a-4c9e-bfc5-9b007c68e21a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9d6f0305-ce05-4bad-a836-1d34e5a9b8ec",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ce886a78-dbb6-47eb-b72b-1ce2ed31091b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0697a46c-0b91-4e70-877b-4a01f3229188",
                "ordinal": 3
              }
            ],
            "lineageTag": "4ff32f42-b292-49f7-a075-af2588c400be"
          }
        ],
        "isHidden": true,
        "lineageTag": "9ff792bb-183d-4e46-9bca-2c552fa74db3",
        "partitions": [
          {
            "name": "LocalDateTable_b2397acb-0929-4697-96e3-a6662f7a4a3c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendario'[Ano-Mês])), 1, 1), Date(Year(MAX('dCalendario'[Ano-Mês])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dPagamentos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id_pagamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc85102b-f350-4908-8463-3b886115bdb9",
            "sourceColumn": "id_pagamento",
            "summarizeBy": "none"
          },
          {
            "name": "id_venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67c5e731-b90e-4491-aff5-2b3c1ec5cc0a",
            "sourceColumn": "id_venda",
            "summarizeBy": "none"
          },
          {
            "name": "forma_pagamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9213a8e6-f228-4c3c-8012-63df66bbf613",
            "sourceColumn": "forma_pagamento",
            "summarizeBy": "none"
          },
          {
            "name": "status_pagamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0b55e5e-12e5-47d9-9f71-c127ba31c311",
            "sourceColumn": "status_pagamento",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "66ea106b-8c1d-4611-af28-f6587fa516df",
        "partitions": [
          {
            "name": "dPagamentos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Web.BrowserContents(\"https://docs.google.com/spreadsheets/d/e/2PACX-1vQcA7MuyQioSGW9kBkg0HzGaQRkuHdjZk4cQf1pEZ5fPVv_lg6D2oFt2sHHixhgtw/pubhtml\"),",
                "    #\"Extracted Table From Html\" = Html.Table(Source, {{\"Column1\", \"DIV:nth-child(5) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(1)\"}, {\"Column2\", \"DIV:nth-child(5) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(2)\"}, {\"Column3\", \"DIV:nth-child(5) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(3)\"}, {\"Column4\", \"DIV:nth-child(5) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(4)\"}, {\"Column5\", \"DIV:nth-child(5) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(5)\"}, {\"Column6\", \"DIV:nth-child(5) > DIV.ritz.grid-container > TABLE.waffle > * > TR > :nth-child(6)\"}}, [RowSelector=\"DIV:nth-child(5) > DIV.ritz.grid-container > TABLE.waffle > * > TR\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Extracted Table From Html\",{{\"Column1\", Int64.Type}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Changed Type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Removed Blank Rows\", [PromoteAllScalars=true]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Promoted Headers\",{\"1\", \"Column6\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72902515-5157-4787-8630-29738e9a62ce",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4aeda695-dc10-43d1-b0bd-d313b7d8563d",
        "measures": [
          {
            "name": "faturamento_total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "SUM(fVendas[valor_total])",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "feba9e81-c19a-4493-8af2-f70b4ff2a527"
          },
          {
            "name": "ticket_medio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "MEDIAN(fVendas[valor_total])",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "06fef05c-0aad-429d-a9ef-376c53d74aca"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}